### ISSUE TITLE
 Improve privacy

### ISSUE THREAD

**Issue by NeodarZ** [Azgaar/Fantasy-Map-Generator-alpha#2]
Hi,

first thanks for your great work with this tool.

Okay it's an alpha but maybe is a better idea to keep the Google Tag Manager in option instead of use it all the time no ?

**Comment by Azgaar** [comment]
Hi @NeodarZ,

I far as I understand Google Tag does not collect personal data. It's just a general statistics. 

Regards,
Azgaar

**Comment by Azgaar** [comment]
Closing as Alpha is published as a Stable version

**Comment by NeodarZ** [comment]
Hi,

In some case the address IP can be identified as a personal data so Google Tag (and another internet service who use IP protocol) collect personal data.

For European Union, where I live, the IP address is a personal data. (true for fixed IP address, not clear with dynamic IP address).

For the moment it's okay to keep this but it's better to use an option for this use case.

**Comment by Azgaar** [comment]
Interesting. How can I toggle gtag for some users only?

**Comment by NeodarZ** [comment]
What I suggesting is to set an option in the menu of your current web application for toggle it.

For example if user accept to send data to Google you can add the JavaScript script who contains the Google request (I speak of this lines: https://github.com/Azgaar/Fantasy-Map-Generator-alpha/blob/master/index.html#L6-L12).
I don't know if it's the best way to do it technically but the idea is that must be disabled by default. Because for EU users you must respect GDPR.

You can also don't use Google Tag Manager because it's much easier to implement. ;)

**Comment by Azgaar** [comment]
To toggle the analytics for EU user I need to check if the user is from EU. I don't see any IPs on Google Analytics, how can I use this info if I don'r have an access to it? We don't have a lot of EU users, so I'm not sure I should worry about it.

**Comment by NeodarZ** [comment]
Hi,

You can't view it, only Google can view it. Yes for you the law is not a problem for the moment. And I don't think for the moment it's important but keep in mind that some user care about their privacy.

That why for me the best idea is don't put your Google Tag Manager id in source-code hosted on github. On your production server where the actual demo is, it's ok.

**Comment by Azgaar** [comment]
Ok, I will consider removing the analytics.

**Comment by Azgaar** [comment]
Removed
